-- GENERATED by C->Haskell Compiler, version 0.28.8 Switcheroo, 25 November 2017 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}
{-# LANGUAGE EmptyDataDecls #-}
{-# LANGUAGE ForeignFunctionInterface #-}



-- Enumerations

data TB_ACCOUNT_FLAGS = TbAccountLinked
                      | TbAccountDebitsMustNotExceedCredits
                      | TbAccountCreditsMustNotExceedDebits
                      | TbAccountHistory
                      | TbAccountImported
                      | TbAccountClosed
  deriving (Eq)
instance Enum TB_ACCOUNT_FLAGS where
  succ TbAccountLinked = TbAccountDebitsMustNotExceedCredits
  succ TbAccountDebitsMustNotExceedCredits = TbAccountCreditsMustNotExceedDebits
  succ TbAccountCreditsMustNotExceedDebits = TbAccountHistory
  succ TbAccountHistory = TbAccountImported
  succ TbAccountImported = TbAccountClosed
  succ TbAccountClosed = error "TB_ACCOUNT_FLAGS.succ: TbAccountClosed has no successor"

  pred TbAccountDebitsMustNotExceedCredits = TbAccountLinked
  pred TbAccountCreditsMustNotExceedDebits = TbAccountDebitsMustNotExceedCredits
  pred TbAccountHistory = TbAccountCreditsMustNotExceedDebits
  pred TbAccountImported = TbAccountHistory
  pred TbAccountClosed = TbAccountImported
  pred TbAccountLinked = error "TB_ACCOUNT_FLAGS.pred: TbAccountLinked has no predecessor"

  enumFromTo from to = go from
    where
      end = fromEnum to
      go v = case compare (fromEnum v) end of
                 LT -> v : go (succ v)
                 EQ -> [v]
                 GT -> []

  enumFrom from = enumFromTo from TbAccountClosed

  fromEnum TbAccountLinked = 1
  fromEnum TbAccountDebitsMustNotExceedCredits = 2
  fromEnum TbAccountCreditsMustNotExceedDebits = 4
  fromEnum TbAccountHistory = 8
  fromEnum TbAccountImported = 16
  fromEnum TbAccountClosed = 32

  toEnum 1 = TbAccountLinked
  toEnum 2 = TbAccountDebitsMustNotExceedCredits
  toEnum 4 = TbAccountCreditsMustNotExceedDebits
  toEnum 8 = TbAccountHistory
  toEnum 16 = TbAccountImported
  toEnum 32 = TbAccountClosed
  toEnum unmatched = error ("TB_ACCOUNT_FLAGS.toEnum: Cannot match " ++ show unmatched)

{-# LINE 8 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}


data TB_TRANSFER_FLAGS = TbTransferLinked
                       | TbTransferPending
                       | TbTransferPostPendingTransfer
                       | TbTransferVoidPendingTransfer
                       | TbTransferBalancingDebit
                       | TbTransferBalancingCredit
                       | TbTransferClosingDebit
                       | TbTransferClosingCredit
                       | TbTransferImported
  deriving (Eq)
instance Enum TB_TRANSFER_FLAGS where
  succ TbTransferLinked = TbTransferPending
  succ TbTransferPending = TbTransferPostPendingTransfer
  succ TbTransferPostPendingTransfer = TbTransferVoidPendingTransfer
  succ TbTransferVoidPendingTransfer = TbTransferBalancingDebit
  succ TbTransferBalancingDebit = TbTransferBalancingCredit
  succ TbTransferBalancingCredit = TbTransferClosingDebit
  succ TbTransferClosingDebit = TbTransferClosingCredit
  succ TbTransferClosingCredit = TbTransferImported
  succ TbTransferImported = error "TB_TRANSFER_FLAGS.succ: TbTransferImported has no successor"

  pred TbTransferPending = TbTransferLinked
  pred TbTransferPostPendingTransfer = TbTransferPending
  pred TbTransferVoidPendingTransfer = TbTransferPostPendingTransfer
  pred TbTransferBalancingDebit = TbTransferVoidPendingTransfer
  pred TbTransferBalancingCredit = TbTransferBalancingDebit
  pred TbTransferClosingDebit = TbTransferBalancingCredit
  pred TbTransferClosingCredit = TbTransferClosingDebit
  pred TbTransferImported = TbTransferClosingCredit
  pred TbTransferLinked = error "TB_TRANSFER_FLAGS.pred: TbTransferLinked has no predecessor"

  enumFromTo from to = go from
    where
      end = fromEnum to
      go v = case compare (fromEnum v) end of
                 LT -> v : go (succ v)
                 EQ -> [v]
                 GT -> []

  enumFrom from = enumFromTo from TbTransferImported

  fromEnum TbTransferLinked = 1
  fromEnum TbTransferPending = 2
  fromEnum TbTransferPostPendingTransfer = 4
  fromEnum TbTransferVoidPendingTransfer = 8
  fromEnum TbTransferBalancingDebit = 16
  fromEnum TbTransferBalancingCredit = 32
  fromEnum TbTransferClosingDebit = 64
  fromEnum TbTransferClosingCredit = 128
  fromEnum TbTransferImported = 256

  toEnum 1 = TbTransferLinked
  toEnum 2 = TbTransferPending
  toEnum 4 = TbTransferPostPendingTransfer
  toEnum 8 = TbTransferVoidPendingTransfer
  toEnum 16 = TbTransferBalancingDebit
  toEnum 32 = TbTransferBalancingCredit
  toEnum 64 = TbTransferClosingDebit
  toEnum 128 = TbTransferClosingCredit
  toEnum 256 = TbTransferImported
  toEnum unmatched = error ("TB_TRANSFER_FLAGS.toEnum: Cannot match " ++ show unmatched)

{-# LINE 10 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}


data TB_CREATE_ACCOUNT_RESULT = TbCreateAccountOk
                              | TbCreateAccountLinkedEventFailed
                              | TbCreateAccountLinkedEventChainOpen
                              | TbCreateAccountTimestampMustBeZero
                              | TbCreateAccountReservedField
                              | TbCreateAccountReservedFlag
                              | TbCreateAccountIdMustNotBeZero
                              | TbCreateAccountIdMustNotBeIntMax
                              | TbCreateAccountFlagsAreMutuallyExclusive
                              | TbCreateAccountDebitsPendingMustBeZero
                              | TbCreateAccountDebitsPostedMustBeZero
                              | TbCreateAccountCreditsPendingMustBeZero
                              | TbCreateAccountCreditsPostedMustBeZero
                              | TbCreateAccountLedgerMustNotBeZero
                              | TbCreateAccountCodeMustNotBeZero
                              | TbCreateAccountExistsWithDifferentFlags
                              | TbCreateAccountExistsWithDifferentUserData128
                              | TbCreateAccountExistsWithDifferentUserData64
                              | TbCreateAccountExistsWithDifferentUserData32
                              | TbCreateAccountExistsWithDifferentLedger
                              | TbCreateAccountExistsWithDifferentCode
                              | TbCreateAccountExists
                              | TbCreateAccountImportedEventExpected
                              | TbCreateAccountImportedEventNotExpected
                              | TbCreateAccountImportedEventTimestampOutOfRange
                              | TbCreateAccountImportedEventTimestampMustNotAdvance
                              | TbCreateAccountImportedEventTimestampMustNotRegress
  deriving (Eq)
instance Enum TB_CREATE_ACCOUNT_RESULT where
  succ TbCreateAccountOk = TbCreateAccountLinkedEventFailed
  succ TbCreateAccountLinkedEventFailed = TbCreateAccountLinkedEventChainOpen
  succ TbCreateAccountLinkedEventChainOpen = TbCreateAccountTimestampMustBeZero
  succ TbCreateAccountTimestampMustBeZero = TbCreateAccountReservedField
  succ TbCreateAccountReservedField = TbCreateAccountReservedFlag
  succ TbCreateAccountReservedFlag = TbCreateAccountIdMustNotBeZero
  succ TbCreateAccountIdMustNotBeZero = TbCreateAccountIdMustNotBeIntMax
  succ TbCreateAccountIdMustNotBeIntMax = TbCreateAccountFlagsAreMutuallyExclusive
  succ TbCreateAccountFlagsAreMutuallyExclusive = TbCreateAccountDebitsPendingMustBeZero
  succ TbCreateAccountDebitsPendingMustBeZero = TbCreateAccountDebitsPostedMustBeZero
  succ TbCreateAccountDebitsPostedMustBeZero = TbCreateAccountCreditsPendingMustBeZero
  succ TbCreateAccountCreditsPendingMustBeZero = TbCreateAccountCreditsPostedMustBeZero
  succ TbCreateAccountCreditsPostedMustBeZero = TbCreateAccountLedgerMustNotBeZero
  succ TbCreateAccountLedgerMustNotBeZero = TbCreateAccountCodeMustNotBeZero
  succ TbCreateAccountCodeMustNotBeZero = TbCreateAccountExistsWithDifferentFlags
  succ TbCreateAccountExistsWithDifferentFlags = TbCreateAccountExistsWithDifferentUserData128
  succ TbCreateAccountExistsWithDifferentUserData128 = TbCreateAccountExistsWithDifferentUserData64
  succ TbCreateAccountExistsWithDifferentUserData64 = TbCreateAccountExistsWithDifferentUserData32
  succ TbCreateAccountExistsWithDifferentUserData32 = TbCreateAccountExistsWithDifferentLedger
  succ TbCreateAccountExistsWithDifferentLedger = TbCreateAccountExistsWithDifferentCode
  succ TbCreateAccountExistsWithDifferentCode = TbCreateAccountExists
  succ TbCreateAccountExists = TbCreateAccountImportedEventExpected
  succ TbCreateAccountImportedEventExpected = TbCreateAccountImportedEventNotExpected
  succ TbCreateAccountImportedEventNotExpected = TbCreateAccountImportedEventTimestampOutOfRange
  succ TbCreateAccountImportedEventTimestampOutOfRange = TbCreateAccountImportedEventTimestampMustNotAdvance
  succ TbCreateAccountImportedEventTimestampMustNotAdvance = TbCreateAccountImportedEventTimestampMustNotRegress
  succ TbCreateAccountImportedEventTimestampMustNotRegress = error "TB_CREATE_ACCOUNT_RESULT.succ: TbCreateAccountImportedEventTimestampMustNotRegress has no successor"

  pred TbCreateAccountLinkedEventFailed = TbCreateAccountOk
  pred TbCreateAccountLinkedEventChainOpen = TbCreateAccountLinkedEventFailed
  pred TbCreateAccountTimestampMustBeZero = TbCreateAccountLinkedEventChainOpen
  pred TbCreateAccountReservedField = TbCreateAccountTimestampMustBeZero
  pred TbCreateAccountReservedFlag = TbCreateAccountReservedField
  pred TbCreateAccountIdMustNotBeZero = TbCreateAccountReservedFlag
  pred TbCreateAccountIdMustNotBeIntMax = TbCreateAccountIdMustNotBeZero
  pred TbCreateAccountFlagsAreMutuallyExclusive = TbCreateAccountIdMustNotBeIntMax
  pred TbCreateAccountDebitsPendingMustBeZero = TbCreateAccountFlagsAreMutuallyExclusive
  pred TbCreateAccountDebitsPostedMustBeZero = TbCreateAccountDebitsPendingMustBeZero
  pred TbCreateAccountCreditsPendingMustBeZero = TbCreateAccountDebitsPostedMustBeZero
  pred TbCreateAccountCreditsPostedMustBeZero = TbCreateAccountCreditsPendingMustBeZero
  pred TbCreateAccountLedgerMustNotBeZero = TbCreateAccountCreditsPostedMustBeZero
  pred TbCreateAccountCodeMustNotBeZero = TbCreateAccountLedgerMustNotBeZero
  pred TbCreateAccountExistsWithDifferentFlags = TbCreateAccountCodeMustNotBeZero
  pred TbCreateAccountExistsWithDifferentUserData128 = TbCreateAccountExistsWithDifferentFlags
  pred TbCreateAccountExistsWithDifferentUserData64 = TbCreateAccountExistsWithDifferentUserData128
  pred TbCreateAccountExistsWithDifferentUserData32 = TbCreateAccountExistsWithDifferentUserData64
  pred TbCreateAccountExistsWithDifferentLedger = TbCreateAccountExistsWithDifferentUserData32
  pred TbCreateAccountExistsWithDifferentCode = TbCreateAccountExistsWithDifferentLedger
  pred TbCreateAccountExists = TbCreateAccountExistsWithDifferentCode
  pred TbCreateAccountImportedEventExpected = TbCreateAccountExists
  pred TbCreateAccountImportedEventNotExpected = TbCreateAccountImportedEventExpected
  pred TbCreateAccountImportedEventTimestampOutOfRange = TbCreateAccountImportedEventNotExpected
  pred TbCreateAccountImportedEventTimestampMustNotAdvance = TbCreateAccountImportedEventTimestampOutOfRange
  pred TbCreateAccountImportedEventTimestampMustNotRegress = TbCreateAccountImportedEventTimestampMustNotAdvance
  pred TbCreateAccountOk = error "TB_CREATE_ACCOUNT_RESULT.pred: TbCreateAccountOk has no predecessor"

  enumFromTo from to = go from
    where
      end = fromEnum to
      go v = case compare (fromEnum v) end of
                 LT -> v : go (succ v)
                 EQ -> [v]
                 GT -> []

  enumFrom from = enumFromTo from TbCreateAccountImportedEventTimestampMustNotRegress

  fromEnum TbCreateAccountOk = 0
  fromEnum TbCreateAccountLinkedEventFailed = 1
  fromEnum TbCreateAccountLinkedEventChainOpen = 2
  fromEnum TbCreateAccountTimestampMustBeZero = 3
  fromEnum TbCreateAccountReservedField = 4
  fromEnum TbCreateAccountReservedFlag = 5
  fromEnum TbCreateAccountIdMustNotBeZero = 6
  fromEnum TbCreateAccountIdMustNotBeIntMax = 7
  fromEnum TbCreateAccountFlagsAreMutuallyExclusive = 8
  fromEnum TbCreateAccountDebitsPendingMustBeZero = 9
  fromEnum TbCreateAccountDebitsPostedMustBeZero = 10
  fromEnum TbCreateAccountCreditsPendingMustBeZero = 11
  fromEnum TbCreateAccountCreditsPostedMustBeZero = 12
  fromEnum TbCreateAccountLedgerMustNotBeZero = 13
  fromEnum TbCreateAccountCodeMustNotBeZero = 14
  fromEnum TbCreateAccountExistsWithDifferentFlags = 15
  fromEnum TbCreateAccountExistsWithDifferentUserData128 = 16
  fromEnum TbCreateAccountExistsWithDifferentUserData64 = 17
  fromEnum TbCreateAccountExistsWithDifferentUserData32 = 18
  fromEnum TbCreateAccountExistsWithDifferentLedger = 19
  fromEnum TbCreateAccountExistsWithDifferentCode = 20
  fromEnum TbCreateAccountExists = 21
  fromEnum TbCreateAccountImportedEventExpected = 22
  fromEnum TbCreateAccountImportedEventNotExpected = 23
  fromEnum TbCreateAccountImportedEventTimestampOutOfRange = 24
  fromEnum TbCreateAccountImportedEventTimestampMustNotAdvance = 25
  fromEnum TbCreateAccountImportedEventTimestampMustNotRegress = 26

  toEnum 0 = TbCreateAccountOk
  toEnum 1 = TbCreateAccountLinkedEventFailed
  toEnum 2 = TbCreateAccountLinkedEventChainOpen
  toEnum 3 = TbCreateAccountTimestampMustBeZero
  toEnum 4 = TbCreateAccountReservedField
  toEnum 5 = TbCreateAccountReservedFlag
  toEnum 6 = TbCreateAccountIdMustNotBeZero
  toEnum 7 = TbCreateAccountIdMustNotBeIntMax
  toEnum 8 = TbCreateAccountFlagsAreMutuallyExclusive
  toEnum 9 = TbCreateAccountDebitsPendingMustBeZero
  toEnum 10 = TbCreateAccountDebitsPostedMustBeZero
  toEnum 11 = TbCreateAccountCreditsPendingMustBeZero
  toEnum 12 = TbCreateAccountCreditsPostedMustBeZero
  toEnum 13 = TbCreateAccountLedgerMustNotBeZero
  toEnum 14 = TbCreateAccountCodeMustNotBeZero
  toEnum 15 = TbCreateAccountExistsWithDifferentFlags
  toEnum 16 = TbCreateAccountExistsWithDifferentUserData128
  toEnum 17 = TbCreateAccountExistsWithDifferentUserData64
  toEnum 18 = TbCreateAccountExistsWithDifferentUserData32
  toEnum 19 = TbCreateAccountExistsWithDifferentLedger
  toEnum 20 = TbCreateAccountExistsWithDifferentCode
  toEnum 21 = TbCreateAccountExists
  toEnum 22 = TbCreateAccountImportedEventExpected
  toEnum 23 = TbCreateAccountImportedEventNotExpected
  toEnum 24 = TbCreateAccountImportedEventTimestampOutOfRange
  toEnum 25 = TbCreateAccountImportedEventTimestampMustNotAdvance
  toEnum 26 = TbCreateAccountImportedEventTimestampMustNotRegress
  toEnum unmatched = error ("TB_CREATE_ACCOUNT_RESULT.toEnum: Cannot match " ++ show unmatched)

{-# LINE 12 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}


data TB_CREATE_TRANSFER_RESULT = TbCreateTransferOk
                               | TbCreateTransferLinkedEventFailed
                               | TbCreateTransferLinkedEventChainOpen
                               | TbCreateTransferTimestampMustBeZero
                               | TbCreateTransferReservedFlag
                               | TbCreateTransferIdMustNotBeZero
                               | TbCreateTransferIdMustNotBeIntMax
                               | TbCreateTransferFlagsAreMutuallyExclusive
                               | TbCreateTransferDebitAccountIdMustNotBeZero
                               | TbCreateTransferDebitAccountIdMustNotBeIntMax
                               | TbCreateTransferCreditAccountIdMustNotBeZero
                               | TbCreateTransferCreditAccountIdMustNotBeIntMax
                               | TbCreateTransferAccountsMustBeDifferent
                               | TbCreateTransferPendingIdMustBeZero
                               | TbCreateTransferPendingIdMustNotBeZero
                               | TbCreateTransferPendingIdMustNotBeIntMax
                               | TbCreateTransferPendingIdMustBeDifferent
                               | TbCreateTransferTimeoutReservedForPendingTransfer
                               | TbCreateTransferAmountMustNotBeZero
                               | TbCreateTransferLedgerMustNotBeZero
                               | TbCreateTransferCodeMustNotBeZero
                               | TbCreateTransferDebitAccountNotFound
                               | TbCreateTransferCreditAccountNotFound
                               | TbCreateTransferAccountsMustHaveTheSameLedger
                               | TbCreateTransferTransferMustHaveTheSameLedgerAsAccounts
                               | TbCreateTransferPendingTransferNotFound
                               | TbCreateTransferPendingTransferNotPending
                               | TbCreateTransferPendingTransferHasDifferentDebitAccountId
                               | TbCreateTransferPendingTransferHasDifferentCreditAccountId
                               | TbCreateTransferPendingTransferHasDifferentLedger
                               | TbCreateTransferPendingTransferHasDifferentCode
                               | TbCreateTransferExceedsPendingTransferAmount
                               | TbCreateTransferPendingTransferHasDifferentAmount
                               | TbCreateTransferPendingTransferAlreadyPosted
                               | TbCreateTransferPendingTransferAlreadyVoided
                               | TbCreateTransferPendingTransferExpired
                               | TbCreateTransferExistsWithDifferentFlags
                               | TbCreateTransferExistsWithDifferentDebitAccountId
                               | TbCreateTransferExistsWithDifferentCreditAccountId
                               | TbCreateTransferExistsWithDifferentAmount
                               | TbCreateTransferExistsWithDifferentPendingId
                               | TbCreateTransferExistsWithDifferentUserData128
                               | TbCreateTransferExistsWithDifferentUserData64
                               | TbCreateTransferExistsWithDifferentUserData32
                               | TbCreateTransferExistsWithDifferentTimeout
                               | TbCreateTransferExistsWithDifferentCode
                               | TbCreateTransferExists
                               | TbCreateTransferOverflowsDebitsPending
                               | TbCreateTransferOverflowsCreditsPending
                               | TbCreateTransferOverflowsDebitsPosted
                               | TbCreateTransferOverflowsCreditsPosted
                               | TbCreateTransferOverflowsDebits
                               | TbCreateTransferOverflowsCredits
                               | TbCreateTransferOverflowsTimeout
                               | TbCreateTransferExceedsCredits
                               | TbCreateTransferExceedsDebits
                               | TbCreateTransferImportedEventExpected
                               | TbCreateTransferImportedEventNotExpected
                               | TbCreateTransferImportedEventTimestampOutOfRange
                               | TbCreateTransferImportedEventTimestampMustNotAdvance
                               | TbCreateTransferImportedEventTimestampMustNotRegress
                               | TbCreateTransferImportedEventTimestampMustPostdateDebitAccount
                               | TbCreateTransferImportedEventTimestampMustPostdateCreditAccount
                               | TbCreateTransferImportedEventTimeoutMustBeZero
                               | TbCreateTransferClosingTransferMustBePending
                               | TbCreateTransferDebitAccountAlreadyClosed
                               | TbCreateTransferCreditAccountAlreadyClosed
                               | TbCreateTransferExistsWithDifferentLedger
                               | TbCreateTransferIdAlreadyFailed
  deriving (Eq)
instance Enum TB_CREATE_TRANSFER_RESULT where
  succ TbCreateTransferOk = TbCreateTransferLinkedEventFailed
  succ TbCreateTransferLinkedEventFailed = TbCreateTransferLinkedEventChainOpen
  succ TbCreateTransferLinkedEventChainOpen = TbCreateTransferTimestampMustBeZero
  succ TbCreateTransferTimestampMustBeZero = TbCreateTransferReservedFlag
  succ TbCreateTransferReservedFlag = TbCreateTransferIdMustNotBeZero
  succ TbCreateTransferIdMustNotBeZero = TbCreateTransferIdMustNotBeIntMax
  succ TbCreateTransferIdMustNotBeIntMax = TbCreateTransferFlagsAreMutuallyExclusive
  succ TbCreateTransferFlagsAreMutuallyExclusive = TbCreateTransferDebitAccountIdMustNotBeZero
  succ TbCreateTransferDebitAccountIdMustNotBeZero = TbCreateTransferDebitAccountIdMustNotBeIntMax
  succ TbCreateTransferDebitAccountIdMustNotBeIntMax = TbCreateTransferCreditAccountIdMustNotBeZero
  succ TbCreateTransferCreditAccountIdMustNotBeZero = TbCreateTransferCreditAccountIdMustNotBeIntMax
  succ TbCreateTransferCreditAccountIdMustNotBeIntMax = TbCreateTransferAccountsMustBeDifferent
  succ TbCreateTransferAccountsMustBeDifferent = TbCreateTransferPendingIdMustBeZero
  succ TbCreateTransferPendingIdMustBeZero = TbCreateTransferPendingIdMustNotBeZero
  succ TbCreateTransferPendingIdMustNotBeZero = TbCreateTransferPendingIdMustNotBeIntMax
  succ TbCreateTransferPendingIdMustNotBeIntMax = TbCreateTransferPendingIdMustBeDifferent
  succ TbCreateTransferPendingIdMustBeDifferent = TbCreateTransferTimeoutReservedForPendingTransfer
  succ TbCreateTransferTimeoutReservedForPendingTransfer = TbCreateTransferAmountMustNotBeZero
  succ TbCreateTransferAmountMustNotBeZero = TbCreateTransferLedgerMustNotBeZero
  succ TbCreateTransferLedgerMustNotBeZero = TbCreateTransferCodeMustNotBeZero
  succ TbCreateTransferCodeMustNotBeZero = TbCreateTransferDebitAccountNotFound
  succ TbCreateTransferDebitAccountNotFound = TbCreateTransferCreditAccountNotFound
  succ TbCreateTransferCreditAccountNotFound = TbCreateTransferAccountsMustHaveTheSameLedger
  succ TbCreateTransferAccountsMustHaveTheSameLedger = TbCreateTransferTransferMustHaveTheSameLedgerAsAccounts
  succ TbCreateTransferTransferMustHaveTheSameLedgerAsAccounts = TbCreateTransferPendingTransferNotFound
  succ TbCreateTransferPendingTransferNotFound = TbCreateTransferPendingTransferNotPending
  succ TbCreateTransferPendingTransferNotPending = TbCreateTransferPendingTransferHasDifferentDebitAccountId
  succ TbCreateTransferPendingTransferHasDifferentDebitAccountId = TbCreateTransferPendingTransferHasDifferentCreditAccountId
  succ TbCreateTransferPendingTransferHasDifferentCreditAccountId = TbCreateTransferPendingTransferHasDifferentLedger
  succ TbCreateTransferPendingTransferHasDifferentLedger = TbCreateTransferPendingTransferHasDifferentCode
  succ TbCreateTransferPendingTransferHasDifferentCode = TbCreateTransferExceedsPendingTransferAmount
  succ TbCreateTransferExceedsPendingTransferAmount = TbCreateTransferPendingTransferHasDifferentAmount
  succ TbCreateTransferPendingTransferHasDifferentAmount = TbCreateTransferPendingTransferAlreadyPosted
  succ TbCreateTransferPendingTransferAlreadyPosted = TbCreateTransferPendingTransferAlreadyVoided
  succ TbCreateTransferPendingTransferAlreadyVoided = TbCreateTransferPendingTransferExpired
  succ TbCreateTransferPendingTransferExpired = TbCreateTransferExistsWithDifferentFlags
  succ TbCreateTransferExistsWithDifferentFlags = TbCreateTransferExistsWithDifferentDebitAccountId
  succ TbCreateTransferExistsWithDifferentDebitAccountId = TbCreateTransferExistsWithDifferentCreditAccountId
  succ TbCreateTransferExistsWithDifferentCreditAccountId = TbCreateTransferExistsWithDifferentAmount
  succ TbCreateTransferExistsWithDifferentAmount = TbCreateTransferExistsWithDifferentPendingId
  succ TbCreateTransferExistsWithDifferentPendingId = TbCreateTransferExistsWithDifferentUserData128
  succ TbCreateTransferExistsWithDifferentUserData128 = TbCreateTransferExistsWithDifferentUserData64
  succ TbCreateTransferExistsWithDifferentUserData64 = TbCreateTransferExistsWithDifferentUserData32
  succ TbCreateTransferExistsWithDifferentUserData32 = TbCreateTransferExistsWithDifferentTimeout
  succ TbCreateTransferExistsWithDifferentTimeout = TbCreateTransferExistsWithDifferentCode
  succ TbCreateTransferExistsWithDifferentCode = TbCreateTransferExists
  succ TbCreateTransferExists = TbCreateTransferOverflowsDebitsPending
  succ TbCreateTransferOverflowsDebitsPending = TbCreateTransferOverflowsCreditsPending
  succ TbCreateTransferOverflowsCreditsPending = TbCreateTransferOverflowsDebitsPosted
  succ TbCreateTransferOverflowsDebitsPosted = TbCreateTransferOverflowsCreditsPosted
  succ TbCreateTransferOverflowsCreditsPosted = TbCreateTransferOverflowsDebits
  succ TbCreateTransferOverflowsDebits = TbCreateTransferOverflowsCredits
  succ TbCreateTransferOverflowsCredits = TbCreateTransferOverflowsTimeout
  succ TbCreateTransferOverflowsTimeout = TbCreateTransferExceedsCredits
  succ TbCreateTransferExceedsCredits = TbCreateTransferExceedsDebits
  succ TbCreateTransferExceedsDebits = TbCreateTransferImportedEventExpected
  succ TbCreateTransferImportedEventExpected = TbCreateTransferImportedEventNotExpected
  succ TbCreateTransferImportedEventNotExpected = TbCreateTransferImportedEventTimestampOutOfRange
  succ TbCreateTransferImportedEventTimestampOutOfRange = TbCreateTransferImportedEventTimestampMustNotAdvance
  succ TbCreateTransferImportedEventTimestampMustNotAdvance = TbCreateTransferImportedEventTimestampMustNotRegress
  succ TbCreateTransferImportedEventTimestampMustNotRegress = TbCreateTransferImportedEventTimestampMustPostdateDebitAccount
  succ TbCreateTransferImportedEventTimestampMustPostdateDebitAccount = TbCreateTransferImportedEventTimestampMustPostdateCreditAccount
  succ TbCreateTransferImportedEventTimestampMustPostdateCreditAccount = TbCreateTransferImportedEventTimeoutMustBeZero
  succ TbCreateTransferImportedEventTimeoutMustBeZero = TbCreateTransferClosingTransferMustBePending
  succ TbCreateTransferClosingTransferMustBePending = TbCreateTransferDebitAccountAlreadyClosed
  succ TbCreateTransferDebitAccountAlreadyClosed = TbCreateTransferCreditAccountAlreadyClosed
  succ TbCreateTransferCreditAccountAlreadyClosed = TbCreateTransferExistsWithDifferentLedger
  succ TbCreateTransferExistsWithDifferentLedger = TbCreateTransferIdAlreadyFailed
  succ TbCreateTransferIdAlreadyFailed = error "TB_CREATE_TRANSFER_RESULT.succ: TbCreateTransferIdAlreadyFailed has no successor"

  pred TbCreateTransferLinkedEventFailed = TbCreateTransferOk
  pred TbCreateTransferLinkedEventChainOpen = TbCreateTransferLinkedEventFailed
  pred TbCreateTransferTimestampMustBeZero = TbCreateTransferLinkedEventChainOpen
  pred TbCreateTransferReservedFlag = TbCreateTransferTimestampMustBeZero
  pred TbCreateTransferIdMustNotBeZero = TbCreateTransferReservedFlag
  pred TbCreateTransferIdMustNotBeIntMax = TbCreateTransferIdMustNotBeZero
  pred TbCreateTransferFlagsAreMutuallyExclusive = TbCreateTransferIdMustNotBeIntMax
  pred TbCreateTransferDebitAccountIdMustNotBeZero = TbCreateTransferFlagsAreMutuallyExclusive
  pred TbCreateTransferDebitAccountIdMustNotBeIntMax = TbCreateTransferDebitAccountIdMustNotBeZero
  pred TbCreateTransferCreditAccountIdMustNotBeZero = TbCreateTransferDebitAccountIdMustNotBeIntMax
  pred TbCreateTransferCreditAccountIdMustNotBeIntMax = TbCreateTransferCreditAccountIdMustNotBeZero
  pred TbCreateTransferAccountsMustBeDifferent = TbCreateTransferCreditAccountIdMustNotBeIntMax
  pred TbCreateTransferPendingIdMustBeZero = TbCreateTransferAccountsMustBeDifferent
  pred TbCreateTransferPendingIdMustNotBeZero = TbCreateTransferPendingIdMustBeZero
  pred TbCreateTransferPendingIdMustNotBeIntMax = TbCreateTransferPendingIdMustNotBeZero
  pred TbCreateTransferPendingIdMustBeDifferent = TbCreateTransferPendingIdMustNotBeIntMax
  pred TbCreateTransferTimeoutReservedForPendingTransfer = TbCreateTransferPendingIdMustBeDifferent
  pred TbCreateTransferAmountMustNotBeZero = TbCreateTransferTimeoutReservedForPendingTransfer
  pred TbCreateTransferLedgerMustNotBeZero = TbCreateTransferAmountMustNotBeZero
  pred TbCreateTransferCodeMustNotBeZero = TbCreateTransferLedgerMustNotBeZero
  pred TbCreateTransferDebitAccountNotFound = TbCreateTransferCodeMustNotBeZero
  pred TbCreateTransferCreditAccountNotFound = TbCreateTransferDebitAccountNotFound
  pred TbCreateTransferAccountsMustHaveTheSameLedger = TbCreateTransferCreditAccountNotFound
  pred TbCreateTransferTransferMustHaveTheSameLedgerAsAccounts = TbCreateTransferAccountsMustHaveTheSameLedger
  pred TbCreateTransferPendingTransferNotFound = TbCreateTransferTransferMustHaveTheSameLedgerAsAccounts
  pred TbCreateTransferPendingTransferNotPending = TbCreateTransferPendingTransferNotFound
  pred TbCreateTransferPendingTransferHasDifferentDebitAccountId = TbCreateTransferPendingTransferNotPending
  pred TbCreateTransferPendingTransferHasDifferentCreditAccountId = TbCreateTransferPendingTransferHasDifferentDebitAccountId
  pred TbCreateTransferPendingTransferHasDifferentLedger = TbCreateTransferPendingTransferHasDifferentCreditAccountId
  pred TbCreateTransferPendingTransferHasDifferentCode = TbCreateTransferPendingTransferHasDifferentLedger
  pred TbCreateTransferExceedsPendingTransferAmount = TbCreateTransferPendingTransferHasDifferentCode
  pred TbCreateTransferPendingTransferHasDifferentAmount = TbCreateTransferExceedsPendingTransferAmount
  pred TbCreateTransferPendingTransferAlreadyPosted = TbCreateTransferPendingTransferHasDifferentAmount
  pred TbCreateTransferPendingTransferAlreadyVoided = TbCreateTransferPendingTransferAlreadyPosted
  pred TbCreateTransferPendingTransferExpired = TbCreateTransferPendingTransferAlreadyVoided
  pred TbCreateTransferExistsWithDifferentFlags = TbCreateTransferPendingTransferExpired
  pred TbCreateTransferExistsWithDifferentDebitAccountId = TbCreateTransferExistsWithDifferentFlags
  pred TbCreateTransferExistsWithDifferentCreditAccountId = TbCreateTransferExistsWithDifferentDebitAccountId
  pred TbCreateTransferExistsWithDifferentAmount = TbCreateTransferExistsWithDifferentCreditAccountId
  pred TbCreateTransferExistsWithDifferentPendingId = TbCreateTransferExistsWithDifferentAmount
  pred TbCreateTransferExistsWithDifferentUserData128 = TbCreateTransferExistsWithDifferentPendingId
  pred TbCreateTransferExistsWithDifferentUserData64 = TbCreateTransferExistsWithDifferentUserData128
  pred TbCreateTransferExistsWithDifferentUserData32 = TbCreateTransferExistsWithDifferentUserData64
  pred TbCreateTransferExistsWithDifferentTimeout = TbCreateTransferExistsWithDifferentUserData32
  pred TbCreateTransferExistsWithDifferentCode = TbCreateTransferExistsWithDifferentTimeout
  pred TbCreateTransferExists = TbCreateTransferExistsWithDifferentCode
  pred TbCreateTransferOverflowsDebitsPending = TbCreateTransferExists
  pred TbCreateTransferOverflowsCreditsPending = TbCreateTransferOverflowsDebitsPending
  pred TbCreateTransferOverflowsDebitsPosted = TbCreateTransferOverflowsCreditsPending
  pred TbCreateTransferOverflowsCreditsPosted = TbCreateTransferOverflowsDebitsPosted
  pred TbCreateTransferOverflowsDebits = TbCreateTransferOverflowsCreditsPosted
  pred TbCreateTransferOverflowsCredits = TbCreateTransferOverflowsDebits
  pred TbCreateTransferOverflowsTimeout = TbCreateTransferOverflowsCredits
  pred TbCreateTransferExceedsCredits = TbCreateTransferOverflowsTimeout
  pred TbCreateTransferExceedsDebits = TbCreateTransferExceedsCredits
  pred TbCreateTransferImportedEventExpected = TbCreateTransferExceedsDebits
  pred TbCreateTransferImportedEventNotExpected = TbCreateTransferImportedEventExpected
  pred TbCreateTransferImportedEventTimestampOutOfRange = TbCreateTransferImportedEventNotExpected
  pred TbCreateTransferImportedEventTimestampMustNotAdvance = TbCreateTransferImportedEventTimestampOutOfRange
  pred TbCreateTransferImportedEventTimestampMustNotRegress = TbCreateTransferImportedEventTimestampMustNotAdvance
  pred TbCreateTransferImportedEventTimestampMustPostdateDebitAccount = TbCreateTransferImportedEventTimestampMustNotRegress
  pred TbCreateTransferImportedEventTimestampMustPostdateCreditAccount = TbCreateTransferImportedEventTimestampMustPostdateDebitAccount
  pred TbCreateTransferImportedEventTimeoutMustBeZero = TbCreateTransferImportedEventTimestampMustPostdateCreditAccount
  pred TbCreateTransferClosingTransferMustBePending = TbCreateTransferImportedEventTimeoutMustBeZero
  pred TbCreateTransferDebitAccountAlreadyClosed = TbCreateTransferClosingTransferMustBePending
  pred TbCreateTransferCreditAccountAlreadyClosed = TbCreateTransferDebitAccountAlreadyClosed
  pred TbCreateTransferExistsWithDifferentLedger = TbCreateTransferCreditAccountAlreadyClosed
  pred TbCreateTransferIdAlreadyFailed = TbCreateTransferExistsWithDifferentLedger
  pred TbCreateTransferOk = error "TB_CREATE_TRANSFER_RESULT.pred: TbCreateTransferOk has no predecessor"

  enumFromTo from to = go from
    where
      end = fromEnum to
      go v = case compare (fromEnum v) end of
                 LT -> v : go (succ v)
                 EQ -> [v]
                 GT -> []

  enumFrom from = enumFromTo from TbCreateTransferIdAlreadyFailed

  fromEnum TbCreateTransferOk = 0
  fromEnum TbCreateTransferLinkedEventFailed = 1
  fromEnum TbCreateTransferLinkedEventChainOpen = 2
  fromEnum TbCreateTransferTimestampMustBeZero = 3
  fromEnum TbCreateTransferReservedFlag = 4
  fromEnum TbCreateTransferIdMustNotBeZero = 5
  fromEnum TbCreateTransferIdMustNotBeIntMax = 6
  fromEnum TbCreateTransferFlagsAreMutuallyExclusive = 7
  fromEnum TbCreateTransferDebitAccountIdMustNotBeZero = 8
  fromEnum TbCreateTransferDebitAccountIdMustNotBeIntMax = 9
  fromEnum TbCreateTransferCreditAccountIdMustNotBeZero = 10
  fromEnum TbCreateTransferCreditAccountIdMustNotBeIntMax = 11
  fromEnum TbCreateTransferAccountsMustBeDifferent = 12
  fromEnum TbCreateTransferPendingIdMustBeZero = 13
  fromEnum TbCreateTransferPendingIdMustNotBeZero = 14
  fromEnum TbCreateTransferPendingIdMustNotBeIntMax = 15
  fromEnum TbCreateTransferPendingIdMustBeDifferent = 16
  fromEnum TbCreateTransferTimeoutReservedForPendingTransfer = 17
  fromEnum TbCreateTransferAmountMustNotBeZero = 18
  fromEnum TbCreateTransferLedgerMustNotBeZero = 19
  fromEnum TbCreateTransferCodeMustNotBeZero = 20
  fromEnum TbCreateTransferDebitAccountNotFound = 21
  fromEnum TbCreateTransferCreditAccountNotFound = 22
  fromEnum TbCreateTransferAccountsMustHaveTheSameLedger = 23
  fromEnum TbCreateTransferTransferMustHaveTheSameLedgerAsAccounts = 24
  fromEnum TbCreateTransferPendingTransferNotFound = 25
  fromEnum TbCreateTransferPendingTransferNotPending = 26
  fromEnum TbCreateTransferPendingTransferHasDifferentDebitAccountId = 27
  fromEnum TbCreateTransferPendingTransferHasDifferentCreditAccountId = 28
  fromEnum TbCreateTransferPendingTransferHasDifferentLedger = 29
  fromEnum TbCreateTransferPendingTransferHasDifferentCode = 30
  fromEnum TbCreateTransferExceedsPendingTransferAmount = 31
  fromEnum TbCreateTransferPendingTransferHasDifferentAmount = 32
  fromEnum TbCreateTransferPendingTransferAlreadyPosted = 33
  fromEnum TbCreateTransferPendingTransferAlreadyVoided = 34
  fromEnum TbCreateTransferPendingTransferExpired = 35
  fromEnum TbCreateTransferExistsWithDifferentFlags = 36
  fromEnum TbCreateTransferExistsWithDifferentDebitAccountId = 37
  fromEnum TbCreateTransferExistsWithDifferentCreditAccountId = 38
  fromEnum TbCreateTransferExistsWithDifferentAmount = 39
  fromEnum TbCreateTransferExistsWithDifferentPendingId = 40
  fromEnum TbCreateTransferExistsWithDifferentUserData128 = 41
  fromEnum TbCreateTransferExistsWithDifferentUserData64 = 42
  fromEnum TbCreateTransferExistsWithDifferentUserData32 = 43
  fromEnum TbCreateTransferExistsWithDifferentTimeout = 44
  fromEnum TbCreateTransferExistsWithDifferentCode = 45
  fromEnum TbCreateTransferExists = 46
  fromEnum TbCreateTransferOverflowsDebitsPending = 47
  fromEnum TbCreateTransferOverflowsCreditsPending = 48
  fromEnum TbCreateTransferOverflowsDebitsPosted = 49
  fromEnum TbCreateTransferOverflowsCreditsPosted = 50
  fromEnum TbCreateTransferOverflowsDebits = 51
  fromEnum TbCreateTransferOverflowsCredits = 52
  fromEnum TbCreateTransferOverflowsTimeout = 53
  fromEnum TbCreateTransferExceedsCredits = 54
  fromEnum TbCreateTransferExceedsDebits = 55
  fromEnum TbCreateTransferImportedEventExpected = 56
  fromEnum TbCreateTransferImportedEventNotExpected = 57
  fromEnum TbCreateTransferImportedEventTimestampOutOfRange = 58
  fromEnum TbCreateTransferImportedEventTimestampMustNotAdvance = 59
  fromEnum TbCreateTransferImportedEventTimestampMustNotRegress = 60
  fromEnum TbCreateTransferImportedEventTimestampMustPostdateDebitAccount = 61
  fromEnum TbCreateTransferImportedEventTimestampMustPostdateCreditAccount = 62
  fromEnum TbCreateTransferImportedEventTimeoutMustBeZero = 63
  fromEnum TbCreateTransferClosingTransferMustBePending = 64
  fromEnum TbCreateTransferDebitAccountAlreadyClosed = 65
  fromEnum TbCreateTransferCreditAccountAlreadyClosed = 66
  fromEnum TbCreateTransferExistsWithDifferentLedger = 67
  fromEnum TbCreateTransferIdAlreadyFailed = 68

  toEnum 0 = TbCreateTransferOk
  toEnum 1 = TbCreateTransferLinkedEventFailed
  toEnum 2 = TbCreateTransferLinkedEventChainOpen
  toEnum 3 = TbCreateTransferTimestampMustBeZero
  toEnum 4 = TbCreateTransferReservedFlag
  toEnum 5 = TbCreateTransferIdMustNotBeZero
  toEnum 6 = TbCreateTransferIdMustNotBeIntMax
  toEnum 7 = TbCreateTransferFlagsAreMutuallyExclusive
  toEnum 8 = TbCreateTransferDebitAccountIdMustNotBeZero
  toEnum 9 = TbCreateTransferDebitAccountIdMustNotBeIntMax
  toEnum 10 = TbCreateTransferCreditAccountIdMustNotBeZero
  toEnum 11 = TbCreateTransferCreditAccountIdMustNotBeIntMax
  toEnum 12 = TbCreateTransferAccountsMustBeDifferent
  toEnum 13 = TbCreateTransferPendingIdMustBeZero
  toEnum 14 = TbCreateTransferPendingIdMustNotBeZero
  toEnum 15 = TbCreateTransferPendingIdMustNotBeIntMax
  toEnum 16 = TbCreateTransferPendingIdMustBeDifferent
  toEnum 17 = TbCreateTransferTimeoutReservedForPendingTransfer
  toEnum 18 = TbCreateTransferAmountMustNotBeZero
  toEnum 19 = TbCreateTransferLedgerMustNotBeZero
  toEnum 20 = TbCreateTransferCodeMustNotBeZero
  toEnum 21 = TbCreateTransferDebitAccountNotFound
  toEnum 22 = TbCreateTransferCreditAccountNotFound
  toEnum 23 = TbCreateTransferAccountsMustHaveTheSameLedger
  toEnum 24 = TbCreateTransferTransferMustHaveTheSameLedgerAsAccounts
  toEnum 25 = TbCreateTransferPendingTransferNotFound
  toEnum 26 = TbCreateTransferPendingTransferNotPending
  toEnum 27 = TbCreateTransferPendingTransferHasDifferentDebitAccountId
  toEnum 28 = TbCreateTransferPendingTransferHasDifferentCreditAccountId
  toEnum 29 = TbCreateTransferPendingTransferHasDifferentLedger
  toEnum 30 = TbCreateTransferPendingTransferHasDifferentCode
  toEnum 31 = TbCreateTransferExceedsPendingTransferAmount
  toEnum 32 = TbCreateTransferPendingTransferHasDifferentAmount
  toEnum 33 = TbCreateTransferPendingTransferAlreadyPosted
  toEnum 34 = TbCreateTransferPendingTransferAlreadyVoided
  toEnum 35 = TbCreateTransferPendingTransferExpired
  toEnum 36 = TbCreateTransferExistsWithDifferentFlags
  toEnum 37 = TbCreateTransferExistsWithDifferentDebitAccountId
  toEnum 38 = TbCreateTransferExistsWithDifferentCreditAccountId
  toEnum 39 = TbCreateTransferExistsWithDifferentAmount
  toEnum 40 = TbCreateTransferExistsWithDifferentPendingId
  toEnum 41 = TbCreateTransferExistsWithDifferentUserData128
  toEnum 42 = TbCreateTransferExistsWithDifferentUserData64
  toEnum 43 = TbCreateTransferExistsWithDifferentUserData32
  toEnum 44 = TbCreateTransferExistsWithDifferentTimeout
  toEnum 45 = TbCreateTransferExistsWithDifferentCode
  toEnum 46 = TbCreateTransferExists
  toEnum 47 = TbCreateTransferOverflowsDebitsPending
  toEnum 48 = TbCreateTransferOverflowsCreditsPending
  toEnum 49 = TbCreateTransferOverflowsDebitsPosted
  toEnum 50 = TbCreateTransferOverflowsCreditsPosted
  toEnum 51 = TbCreateTransferOverflowsDebits
  toEnum 52 = TbCreateTransferOverflowsCredits
  toEnum 53 = TbCreateTransferOverflowsTimeout
  toEnum 54 = TbCreateTransferExceedsCredits
  toEnum 55 = TbCreateTransferExceedsDebits
  toEnum 56 = TbCreateTransferImportedEventExpected
  toEnum 57 = TbCreateTransferImportedEventNotExpected
  toEnum 58 = TbCreateTransferImportedEventTimestampOutOfRange
  toEnum 59 = TbCreateTransferImportedEventTimestampMustNotAdvance
  toEnum 60 = TbCreateTransferImportedEventTimestampMustNotRegress
  toEnum 61 = TbCreateTransferImportedEventTimestampMustPostdateDebitAccount
  toEnum 62 = TbCreateTransferImportedEventTimestampMustPostdateCreditAccount
  toEnum 63 = TbCreateTransferImportedEventTimeoutMustBeZero
  toEnum 64 = TbCreateTransferClosingTransferMustBePending
  toEnum 65 = TbCreateTransferDebitAccountAlreadyClosed
  toEnum 66 = TbCreateTransferCreditAccountAlreadyClosed
  toEnum 67 = TbCreateTransferExistsWithDifferentLedger
  toEnum 68 = TbCreateTransferIdAlreadyFailed
  toEnum unmatched = error ("TB_CREATE_TRANSFER_RESULT.toEnum: Cannot match " ++ show unmatched)

{-# LINE 14 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}


data TB_ACCOUNT_FILTER_FLAGS = TbAccountFilterDebits
                             | TbAccountFilterCredits
                             | TbAccountFilterReversed
  deriving (Eq)
instance Enum TB_ACCOUNT_FILTER_FLAGS where
  succ TbAccountFilterDebits = TbAccountFilterCredits
  succ TbAccountFilterCredits = TbAccountFilterReversed
  succ TbAccountFilterReversed = error "TB_ACCOUNT_FILTER_FLAGS.succ: TbAccountFilterReversed has no successor"

  pred TbAccountFilterCredits = TbAccountFilterDebits
  pred TbAccountFilterReversed = TbAccountFilterCredits
  pred TbAccountFilterDebits = error "TB_ACCOUNT_FILTER_FLAGS.pred: TbAccountFilterDebits has no predecessor"

  enumFromTo from to = go from
    where
      end = fromEnum to
      go v = case compare (fromEnum v) end of
                 LT -> v : go (succ v)
                 EQ -> [v]
                 GT -> []

  enumFrom from = enumFromTo from TbAccountFilterReversed

  fromEnum TbAccountFilterDebits = 1
  fromEnum TbAccountFilterCredits = 2
  fromEnum TbAccountFilterReversed = 4

  toEnum 1 = TbAccountFilterDebits
  toEnum 2 = TbAccountFilterCredits
  toEnum 4 = TbAccountFilterReversed
  toEnum unmatched = error ("TB_ACCOUNT_FILTER_FLAGS.toEnum: Cannot match " ++ show unmatched)

{-# LINE 16 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}


data TB_OPERATION = TbOperationPulse
                  | TbOperationCreateAccounts
                  | TbOperationCreateTransfers
                  | TbOperationLookupAccounts
                  | TbOperationLookupTransfers
                  | TbOperationGetAccountTransfers
                  | TbOperationGetAccountBalances
                  | TbOperationQueryAccounts
                  | TbOperationQueryTransfers
  deriving (Eq)
instance Enum TB_OPERATION where
  succ TbOperationPulse = TbOperationCreateAccounts
  succ TbOperationCreateAccounts = TbOperationCreateTransfers
  succ TbOperationCreateTransfers = TbOperationLookupAccounts
  succ TbOperationLookupAccounts = TbOperationLookupTransfers
  succ TbOperationLookupTransfers = TbOperationGetAccountTransfers
  succ TbOperationGetAccountTransfers = TbOperationGetAccountBalances
  succ TbOperationGetAccountBalances = TbOperationQueryAccounts
  succ TbOperationQueryAccounts = TbOperationQueryTransfers
  succ TbOperationQueryTransfers = error "TB_OPERATION.succ: TbOperationQueryTransfers has no successor"

  pred TbOperationCreateAccounts = TbOperationPulse
  pred TbOperationCreateTransfers = TbOperationCreateAccounts
  pred TbOperationLookupAccounts = TbOperationCreateTransfers
  pred TbOperationLookupTransfers = TbOperationLookupAccounts
  pred TbOperationGetAccountTransfers = TbOperationLookupTransfers
  pred TbOperationGetAccountBalances = TbOperationGetAccountTransfers
  pred TbOperationQueryAccounts = TbOperationGetAccountBalances
  pred TbOperationQueryTransfers = TbOperationQueryAccounts
  pred TbOperationPulse = error "TB_OPERATION.pred: TbOperationPulse has no predecessor"

  enumFromTo from to = go from
    where
      end = fromEnum to
      go v = case compare (fromEnum v) end of
                 LT -> v : go (succ v)
                 EQ -> [v]
                 GT -> []

  enumFrom from = enumFromTo from TbOperationQueryTransfers

  fromEnum TbOperationPulse = 128
  fromEnum TbOperationCreateAccounts = 129
  fromEnum TbOperationCreateTransfers = 130
  fromEnum TbOperationLookupAccounts = 131
  fromEnum TbOperationLookupTransfers = 132
  fromEnum TbOperationGetAccountTransfers = 133
  fromEnum TbOperationGetAccountBalances = 134
  fromEnum TbOperationQueryAccounts = 135
  fromEnum TbOperationQueryTransfers = 136

  toEnum 128 = TbOperationPulse
  toEnum 129 = TbOperationCreateAccounts
  toEnum 130 = TbOperationCreateTransfers
  toEnum 131 = TbOperationLookupAccounts
  toEnum 132 = TbOperationLookupTransfers
  toEnum 133 = TbOperationGetAccountTransfers
  toEnum 134 = TbOperationGetAccountBalances
  toEnum 135 = TbOperationQueryAccounts
  toEnum 136 = TbOperationQueryTransfers
  toEnum unmatched = error ("TB_OPERATION.toEnum: Cannot match " ++ show unmatched)

{-# LINE 18 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}


data TB_PACKET_STATUS = TbPacketOk
                      | TbPacketTooMuchData
                      | TbPacketClientShutdown
                      | TbPacketInvalidOperation
                      | TbPacketInvalidDataSize
  deriving (Eq)
instance Enum TB_PACKET_STATUS where
  succ TbPacketOk = TbPacketTooMuchData
  succ TbPacketTooMuchData = TbPacketClientShutdown
  succ TbPacketClientShutdown = TbPacketInvalidOperation
  succ TbPacketInvalidOperation = TbPacketInvalidDataSize
  succ TbPacketInvalidDataSize = error "TB_PACKET_STATUS.succ: TbPacketInvalidDataSize has no successor"

  pred TbPacketTooMuchData = TbPacketOk
  pred TbPacketClientShutdown = TbPacketTooMuchData
  pred TbPacketInvalidOperation = TbPacketClientShutdown
  pred TbPacketInvalidDataSize = TbPacketInvalidOperation
  pred TbPacketOk = error "TB_PACKET_STATUS.pred: TbPacketOk has no predecessor"

  enumFromTo from to = go from
    where
      end = fromEnum to
      go v = case compare (fromEnum v) end of
                 LT -> v : go (succ v)
                 EQ -> [v]
                 GT -> []

  enumFrom from = enumFromTo from TbPacketInvalidDataSize

  fromEnum TbPacketOk = 0
  fromEnum TbPacketTooMuchData = 1
  fromEnum TbPacketClientShutdown = 2
  fromEnum TbPacketInvalidOperation = 3
  fromEnum TbPacketInvalidDataSize = 4

  toEnum 0 = TbPacketOk
  toEnum 1 = TbPacketTooMuchData
  toEnum 2 = TbPacketClientShutdown
  toEnum 3 = TbPacketInvalidOperation
  toEnum 4 = TbPacketInvalidDataSize
  toEnum unmatched = error ("TB_PACKET_STATUS.toEnum: Cannot match " ++ show unmatched)

{-# LINE 20 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}


data TB_STATUS = TbStatusSuccess
               | TbStatusUnexpected
               | TbStatusOutOfMemory
               | TbStatusAddressInvalid
               | TbStatusAddressLimitExceeded
               | TbStatusSystemResources
               | TbStatusNetworkSubsystem
  deriving (Eq)
instance Enum TB_STATUS where
  succ TbStatusSuccess = TbStatusUnexpected
  succ TbStatusUnexpected = TbStatusOutOfMemory
  succ TbStatusOutOfMemory = TbStatusAddressInvalid
  succ TbStatusAddressInvalid = TbStatusAddressLimitExceeded
  succ TbStatusAddressLimitExceeded = TbStatusSystemResources
  succ TbStatusSystemResources = TbStatusNetworkSubsystem
  succ TbStatusNetworkSubsystem = error "TB_STATUS.succ: TbStatusNetworkSubsystem has no successor"

  pred TbStatusUnexpected = TbStatusSuccess
  pred TbStatusOutOfMemory = TbStatusUnexpected
  pred TbStatusAddressInvalid = TbStatusOutOfMemory
  pred TbStatusAddressLimitExceeded = TbStatusAddressInvalid
  pred TbStatusSystemResources = TbStatusAddressLimitExceeded
  pred TbStatusNetworkSubsystem = TbStatusSystemResources
  pred TbStatusSuccess = error "TB_STATUS.pred: TbStatusSuccess has no predecessor"

  enumFromTo from to = go from
    where
      end = fromEnum to
      go v = case compare (fromEnum v) end of
                 LT -> v : go (succ v)
                 EQ -> [v]
                 GT -> []

  enumFrom from = enumFromTo from TbStatusNetworkSubsystem

  fromEnum TbStatusSuccess = 0
  fromEnum TbStatusUnexpected = 1
  fromEnum TbStatusOutOfMemory = 2
  fromEnum TbStatusAddressInvalid = 3
  fromEnum TbStatusAddressLimitExceeded = 4
  fromEnum TbStatusSystemResources = 5
  fromEnum TbStatusNetworkSubsystem = 6

  toEnum 0 = TbStatusSuccess
  toEnum 1 = TbStatusUnexpected
  toEnum 2 = TbStatusOutOfMemory
  toEnum 3 = TbStatusAddressInvalid
  toEnum 4 = TbStatusAddressLimitExceeded
  toEnum 5 = TbStatusSystemResources
  toEnum 6 = TbStatusNetworkSubsystem
  toEnum unmatched = error ("TB_STATUS.toEnum: Cannot match " ++ show unmatched)

{-# LINE 22 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}


-- Pointer Types

newtype TbClient = TbClient (C2HSImp.Ptr (TbClient))
{-# LINE 26 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}


import qualified Foreign.Ptr as C2HSImp

