-- GENERATED by C->Haskell Compiler, version 0.28.8 Switcheroo, 25 November 2017 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "src/Database/TigerBeetle/Internal/TbClient.chs" #-}
{-# LANGUAGE ForeignFunctionInterface #-}




